### ISSUE TITLE
Possible error in calculating denominator of component death probabilities

### ISSUE THREAD

**Issue by dtburk** [caseybreen/childhoodmortality#1]
This issue pertains to line 33 in utilities.R, inside the `compute_cdpw()` function. That line currently reads:

`T_den <- df[which(!df$kidagediedimp < (lower_age_segment + 1) | is.na(df$kidagediedimp)), ]`

I think it should look like this:

`T_den <- df[which(df$kidagediedimp >= lower_age_segment | is.na(df$kidagediedimp)), ]`

Take the example of the 0 to 1 month age interval, in other words, `lower_age_segment` = 0. For this interval, the existing code would exclude from the denominator records with `kidagediedimp` less than 1 (in other words, kids who died at age 0 months). It seems those records should be included in the denominator, especially given that they are included in the numerator (see line 25 in utilities.R).

**Comment by caseybreen** [comment]
great catch, thanks!
